// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzqohewfntpnuzdekqoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6cW9oZXdmbnRwbnV6ZGVrcW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTQxMjksImV4cCI6MjA3MTkzMDEyOX0.lP1r5YlTMrwO5k1dDJXmCZl6aNXu_hjGWBWgTrdIcqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});